---

version: '3'
services:
  db:
    image: 'public.ecr.aws/ubuntu/mysql:latest'
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'enjoyotel'
    ports:
      - '33306:3306'
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/conf.d:/etc/mysql/conf.d'
      - './db/init.csv:/docker-entrypoint-initdb.d/init.csv'
      - './db/ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql'
      - './db/import.sh:/docker-entrypoint-initdb.d/02_import.sh'
  zipkin:
    image: 'ghcr.io/openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  otel-collector:
    image: 'ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.68.0'
    ports:
      - '4318:4318'
    volumes:
      - './collector.yml:/etc/otelcol-contrib/config.yaml'
    environment:
      ZIPKIN_ORIGIN: 'http://zipkin:9411'
