---

version: '3'
services:
  db:
    image: 'public.ecr.aws/ubuntu/mysql:latest'
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'enjoyotel'
    ports:
      - '33306:3306'
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/conf.d:/etc/mysql/conf.d'
      - './db/ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql'
      - './db/init.sql:/docker-entrypoint-initdb.d/02_init.sql'
  zipkin:
    image: 'ghcr.io/openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  otel-collector:
    image: 'ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.77.0'
    ports:
      - '4317:4317'
      - '9999:9999'
    volumes:
      - './collector.yml:/etc/otelcol-contrib/config.yaml'
    environment:
      ZIPKIN_ORIGIN: 'http://zipkin:9411'
  prometheus:
    image: 'quay.io/prometheus/prometheus:v2.44.0'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
