directive @authenticate(scopes: [Scope!]) on FIELD_DEFINITION

scalar Time

scalar Cursor

enum Scope {
  READ
  WRITE
}

enum LiverStatus {
  ANNOUNCED
  DEBUTED
  RETIRED
}

type Group {
  name: String!
}

type LiverGroupEdge {
  node: Group!
  cursor: Cursor!
}

type LiverGroupConnetion {
  edges: [LiverGroupEdge!]!
  pageInfo: PageInfo!
}

type Liver {
  name: String!
  debuted_on: Time!
  retired_on: Time
  status: LiverStatus!
  enrollmentDays: Int!
  groups(first: Int, after: Cursor): LiverGroupConnetion!
}

type PageInfo {
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
  startCursor: Cursor
  endCursor: Cursor
}

type LiverEdge {
  node: Liver!
  cursor: Cursor!
}

type LiverConnection {
  edges: [LiverEdge!]!
  pageInfo: PageInfo!
}

enum OrderDirection {
  ASC
  DESC
}

enum LiverOrderField {
  DATABASE_ID
}

input LiverOrder {
  field: LiverOrderField!
  direction: OrderDirection!
}

type Query {
  liver(name: String!): Liver @authenticate(scopes: [READ])
  livers(
    first: Int = 0,
    after: Cursor,
    orderBy: LiverOrder
  ): LiverConnection! @authenticate(scopes: [READ])
}

type Mutation {
  registerLiver(name: String!): Boolean! @authenticate(scopes: [WRITE])
}
