---

name: CI (Go)
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: reviewdog/action-golangci-lint@v2.1.7
        with:
          level: warning
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - ./cmd/web
          - ./cmd/upstream
          - ./cmd/downstream
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3.1.0
        with:
          go-version: 1.19
          cache: true
      - name: build
        run: go build -o out $target
        env:
          target: ${{ matrix.target }}
  publish-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        component:
          - upstream
          - downstream
          - otel-collector
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/${{ matrix.component }}
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./dockerfiles/${{ matrix.component }}.Dockerfile
